### ISSUE TITLE
Get OS X build on travis working

### ISSUE THREAD

**Issue by ruflin** [elastic/topbeat#112]
Currently the build for OS X on Travis is disabled as it fails. The following error happens:

```
/Users/travis/gopath/bin/gotestcover -race -coverprofile=build/coverage/integration.cov -covermode=atomic github.com/elastic/topbeat/...
?   	github.com/elastic/topbeat/test	[no test files]
command [go test -race -cover -covermode atomic -coverprofile /var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/gotestcover-150375732 github.com/elastic/topbeat]: exit status 1
--- FAIL: TestFileSystemList (0.00s)
	Error Trace:	sigar_test.go:135
	Error:		Expected nil, but got: 0x5
		
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x40cb072]
goroutine 4 [running]:
testing.tRunner.func1(0xc8200d4090)
	/private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/workdir/go/src/testing/testing.go:450 +0x1f5
github.com/elastic/topbeat.TestFileSystemList(0xc8200d4090)
	/Users/travis/gopath/src/github.com/elastic/topbeat/sigar_test.go:137 +0x372
testing.tRunner(0xc8200d4090, 0x47cb9a0)
	/private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/workdir/go/src/testing/testing.go:561 +0xaa4
goroutine 1 [chan receive]:
testing.RunTests(0x466b248, 0x47cb8e0, 0xf, 0xf, 0x44f5701)
	/private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/workdir/go/src/testing/testing.go:562 +0xafa
testing.(*M).Run(0xc8200a9ef0, 0x5166820)
	/private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/workdir/go/src/testing/testing.go:494 +0xe5
main.main()
	github.com/elastic/topbeat/_test/_testmain.go:134 +0x385
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/private/var/folders/q8/bf_4b1ts2zj0l7b0p1dv36lr0000gp/T/workdir/go/src/runtime/asm_amd64.s:1696 +0x1
goroutine 20 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x26
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x45
FAIL	github.com/elastic/topbeat	0.067s
test failed
```

**Comment by andrewkroh** [comment]
It works now. Closing.
